services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: openex
      POSTGRES_USER: openex
      POSTGRES_PASSWORD: openex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: