spring:
  security:
    user:
      name: unused
      password: unused

  datasource:
    url: jdbc:postgresql://localhost:5432/openex
    username: openex
    password: openex
  flyway:
    enabled: true 
    